name: Check configuration self hosted

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cp env.example
        run: cp .env.example .env

      - name: Run docker compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Run test with pytest
        run: docker compose exec app poetry run pytest tests
